name: Local Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Using the same VM that hosts the service

    steps:
    - name: Configure Safe Directory
      run: git config --global --add safe.directory /home/nikos/itb/ewc-poc/ewc-wallet-conformance-backend

    - uses: actions/checkout@v2
      name: Checkout code

    - name: Build and Deploy
      run: |
          cd /home/nikos/itb/ewc-poc/ewc-wallet-conformance-backend
          git pull origin main
          docker compose down
          docker compose build
          docker compose up -d
